name: BuildLib

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            flags: ""
          - os: macOS-11
            name: macOS
            flags: ""

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ${{ matrix.flags }} ..

      - name: build
        working-directory: build
        run: cmake --build . --target install --config Release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: build_java
        run: ./gradlew jar

      - name: copy_jar
        working-directory: build/install
        run: cp ../../helixtrajectoryj/build/libs/helixtrajectoryj.jar .

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HelixTrajectory_${{ matrix.os }}
          path: build/install

  build-windows:
    name: "Build - Windows"
    runs-on: windows-2019
    steps:
      # - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: >-
            git
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
          update: true

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: configure_build
        shell: msys2 {0}
        run: |
          cd /C/_
          mkdir build
          cd build
          cmake ..
          cmake --build . --target install --config Release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: build_java
        run: .\gradlew.bat jar

      - name: copy_jar
        working-directory: build/install
        run: copy ../../helixtrajectoryj/build/libs/helixtrajectoryj.jar .

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HelixTrajectory_Windows
          path: build/install