name: BuildLib

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            mingw: false
            cmake_flags: ""
            gradle_command: "./gradlew"

          - os: macOS-11
            name: macOS
            mingw: false
            cmake_flags: ""
            gradle_command: "./gradlew"

          - os: windows-2019
            name: Windows
            mingw: true
            cmake_flags: "-G \"MinGW Makefiles\" -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++"
            gradle_command: ".\\gradlew.bat"

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up MinGW
        if: ${{ matrix.mingw }}
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Configure CMake
        run: mkdir build && cd build && cmake ${{ matrix.cmake_flags }} ..

      - name: Build Makefile
        working-directory: build
        run: cmake --build . --target install --config Release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Build Java
        run: ${{ matrix.gradle_command }} jar

      - name: Copy Jar to Install Dir
        working-directory: build/install
        run: cp ../../helixtrajectoryj/build/libs/helixtrajectoryj.jar .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HelixTrajectory_${{ matrix.os }}
          path: build/install