name: BuildLib

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            flags: ""
          - os: macOS-11
            name: macOS
            container: ""
            flags: ""

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ${{ matrix.flags }} ..

      - name: build
        working-directory: build
        run: cmake --build . --target install --config Release

      - name: compress_artifacts
        run: zip -qq -r HelixTrajectory_${{ matrix.os }}.zip dist include lib
        working-directory: build/install

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HelixTrajectory_${{ matrix.os }}
          path: build/install/HelixTrajectory_${{ matrix.os }}.zip
      
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          architecture: ${{ matrix.architecture }}
      
      - name: build_java
        run: ./gradlew jar