name: BuildLib

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            flags: ""
          - os: macOS-11
            name: macOS
            flags: ""

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ${{ matrix.flags }} ..

      - name: build
        working-directory: build
        run: cmake --build . --target install --config Release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: build_java
        run: ./gradlew jar

      - name: copy_jar
        working-directory: build/install
        run: cp ../../helixtrajectoryj/build/libs/helixtrajectoryj.jar .

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HelixTrajectory_${{ matrix.os }}
          path: build/install

  build-windows:
    name: "Build - Windows"
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      # - name: Install CMake
      #   uses: lukka/get-cmake@v3.23.0

      # - name: Set up Clang
      #   uses: egor-tensin/setup-clang@v1
      #   with:
      #     version: latest
      #     platform: x64

      - name: configure
        run: mkdir build && cd build && cmake ..

      - name: build
        working-directory: build
        run: cmake -DCMAKE_CXX_COMPILER=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\x86_64-w64-mingw32-g++.exe --build . --target install --config Release

      - uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: build_java
        run: .\gradlew.bat jar

      - name: copy_jar
        working-directory: build/install
        run: copy ../../helixtrajectoryj/build/libs/helixtrajectoryj.jar .

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HelixTrajectory_Windows
          path: build/install