name: BuildLib

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            flags: ""
          - os: macOS-11
            name: macOS
            container: ""
            flags: ""

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: mkdir build && cd build && cmake ${{ matrix.flags }} ..

      - name: build
        working-directory: build
        run: cmake --build .

      - name: compress_artifacts
        uses: vimtor/action-zip@v1
        working-directory: build
        with:
          files: install
          dest: HelixTrajectory_${{ matrix.os }}.zip

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        working-directory: build
        with:
          name: HelixTrajectory_${{ matrix.os }}
          path: HelixTrajectory_${{ matrix.os }}.zip